# Generated by Django 5.1.1 on 2024-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_board_project'),
        ('projects', '0010_alter_project_id_alter_projectinvitation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='boards',
            field=models.ManyToManyField(related_name='projects', to='boards.board'),
        ),
    ]
