# Generated by Django 5.1.1 on 2024-11-16 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_boards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='boards',
        ),
    ]
