# Generated by Django 5.1.1 on 2024-10-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_list_max_wip_alter_attachment_id_alter_board_id_and_more'),
        ('projects', '0010_alter_project_id_alter_projectinvitation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
