# Generated by Django 5.1.1 on 2024-11-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_checklisttask_delete_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklisttask',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='board',
            name='project',
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
