# Generated by Django 5.1.1 on 2024-12-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_remove_item_assigned_to_item_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='max_wip',
            field=models.IntegerField(),
        ),
    ]
