# Generated by Django 5.1.1 on 2024-12-24 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_board_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='max_wip',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
