# Generated by Django 5.1.1 on 2024-12-25 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0024_alter_list_max_wip'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.ManyToManyField(blank=True, to='boards.label'),
        ),
        migrations.AlterField(
            model_name='list',
            name='max_wip',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
