# Generated by Django 5.1.1 on 2024-12-26 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_item_labels_alter_list_max_wip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttask',
            name='card',
        ),
        migrations.AddField(
            model_name='item',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
