# Generated by Django 5.1.1 on 2024-12-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0026_remove_checklisttask_card_item_board_delete_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
        ),
    ]
