# Generated by Django 5.1.1 on 2024-12-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0027_alter_item_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='items', to='boards.label'),
        ),
    ]
